name: Upload Website

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.1
      - name: Create S3 Bucket
        id: create-s3-bucket
        run: |
          if [ "${{ steps.branch-name.outputs.current_branch }}" = "main" ]; then
            BUCKET=${{ secrets.AWS_S3_BUCKET }}
          else
            BUCKET=${{ steps.branch-name.outputs.current_branch }}.${{ secrets.AWS_S3_BUCKET }}
          fi
          aws s3 mb s3://$BUCKET
          echo "::set-output name=BUCKET::$BUCKET"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-north-1"
      - uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ steps.create-s3-bucket.outputs.BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-north-1"
          SOURCE_DIR: "src"
